stages:
  - test

tox-tests:
  stage: test
  image: python:${PYTHON_VERSION}
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  before_script:
    - pip install poetry
    - poetry install --no-interaction --no-root
  script:
    - poetry run tox
  cache:
    paths:
      - .tox/
      - .cache/pip/
  parallel:
    matrix:
      - PYTHON_VERSION: [ "3.8", "3.9", "3.10", "3.11", "3.12", "3.13" ]